#!/bin/sh
user=$1
if [ $user == santosh ];then
rm -rf /opt/securef
cat > securef
echo 'A secure file has been cretaed and sent to ur mail'
git status
git add *
git commit -m"$user securefile has been created"
git push origin master
cd ocbcaf
mvn package
cd ..
else
echo 'you are not an ocbc user'
fi

